### ISSUE TITLE
Newest version of library unavailable in gradle

### ISSUE THREAD

**Issue by kubak89** [MagicTheGathering/mtg-sdk-java#12]
Please publish new version of the library to Maven repository.

**Comment by thechucklingatom** [comment]
@nyholmniklas was managing the maven repository stuff, but he doesn't seem to be around currently, so I am looking into everything I need to do in order to get the next release into maven. New thing for me.

**Comment by thechucklingatom** [comment]
I have staged it, and they should be up in a bit, I don't know how long it usually takes to show up but as soon as I see it I will close the issue.

**Comment by nyholmniklas** [comment]
Hey guys! Sorry for inactivity, it's been a busy week.. Glad you figured it out :) Let me know if it doesn't work and I can have a look over the weekend.

**Comment by thechucklingatom** [comment]
No worries, It is available now, I was having key issues, but that is all resolved now, so it should exist now, I see it on the nexus.
