### ISSUE TITLE
Support for card legalities.

### ISSUE THREAD

**Issue by RenanRossiDias** [MagicTheGathering/mtg-sdk-java#15]
First of all, congratulations for the great work done with SDK for android.

In the JSON file there are card legalities, but Card class does not come with such information. 
My suggestion is to add support for card Legality in order to treat such information.

Additionally, an attribute "Card Price" would also save a lot of work when dealing with pricing. 
It could be a primitive type, user setted field, in order to maintain a quick register into the object, instead of externalizing it.

**Comment by thechucklingatom** [comment]
Sounds good, I will work on implementing that. Do you think we want multiple prices, like low med high, and maybe the same for online? I was hoping to get to this tonight but had some car trouble. Might get around to it tomorrow.

**Comment by RenanRossiDias** [comment]
That's a good point. I thought about it for a while, and i think that your suggestion is the best.
Pricing could get complicated if we start talking about printings of a single card and it's values, but as a user setted field , i think that low, med and high should be very usefull and simple.

Hope your car gets good!

**Comment by thechucklingatom** [comment]
Release 0.0.7 is out, which has all the functionality, let me know if you have any questions or suggestions. It should be on maven shortly, and is under the releases on github.
