### ISSUE TITLE
set.getCards(); is returning null 

### ISSUE THREAD

**Issue by BrunoFerreiraBF** [MagicTheGathering/mtg-sdk-java#19]
String setCode = "DRK";
MtgSet set = SetAPI.getSet(setCode);

System.out.println(set.getCards());

is allways null

**Comment by thechucklingatom** [comment]
I plan on taking a look at this one this weekend, thanks for the report.

**Comment by thechucklingatom** [comment]
Fixed in release 0.0.10 by commit f3f7c5ad08e6ff5ec2a2a3be5330ac77b9c89e92

**Comment by T3rrabyte** [comment]
This appears to have stopped working again.

**Comment by thechucklingatom** [comment]
Different issue. That was just for a single set.
