### ISSUE TITLE
Missing european sets

### ISSUE THREAD

**Issue by sebastiandine** [MagicTheGathering/mtg-sdk-java#21]
Europe specific sets like **Foreign Black and White Bordered** as well as **Renaissance** are missing. It seems like they are not maintained by the **magicthegathering.io** API. I already contacted their support several month ago, but still did not receive any answer.

**Comment by thechucklingatom** [comment]
All I do is provide a wrapper for the API, which has the data provided by mtgJson. You can log an issue for them here https://github.com/mtgjson/mtgjson. I know fir the most part they just scrape from gatherer which does not separate those cards into their own set from my understanding.

**Comment by sebastiandine** [comment]
Thanks for the info. I will submit an issue to mtgjson.
