### ISSUE TITLE
set.getCards() returns null in v0.0.10

### ISSUE THREAD

**Issue by T3rrabyte** [MagicTheGathering/mtg-sdk-java#22]
The project I'm currently working on in which this is an issue is here:

https://github.com/T3rrabyte/MTGDS

**Comment by thechucklingatom** [comment]
Is this all sets or a specific set you are getting the error with?

**Comment by T3rrabyte** [comment]
Every set.

**Comment by thechucklingatom** [comment]
Okay, I will take a look hopefully tonight or tomorrow, and will update with additional information as needed.

**Comment by T3rrabyte** [comment]
Thank you for the quick response!

**Comment by thechucklingatom** [comment]
I did not realize you are using getAllSets().get(index).getCards; I am not sure if the rate limits on the api will allow for getting all sets and referencing the cards that way. I am building out a test currently and going to give it a run. It will also drastically slow down the performance of getAllSets, so I may be adding a new method of getAllSetsWithCards();

**Comment by thechucklingatom** [comment]
Should be fixed in ae007cf602a61b30e09f771c630742539e0c2d64 which will be appearing as v0.0.11. There will be a future v0.0.12 release that will also add this functionality to a filter get all sets.
