### ISSUE TITLE
Card.equals() throws NullPointerException

### ISSUE THREAD

**Issue by yannekflick** [MagicTheGathering/mtg-sdk-java#23]
If the Manacost is null, the equals method of class Card throws a NullPointerException. Flipcards like Nicol Bolas (m19) have no manacosts.

**Comment by thechucklingatom** [comment]
Oops, that should be looking at cmc, not Mana cost. I'll build a test out for that and fix it tonight.

**Comment by thechucklingatom** [comment]
I will likely have to change it a bit as well, since there are a few cards that wouldn't have multiverseId's. I will be adding test coverage around that as well.

**Comment by thechucklingatom** [comment]
Should be resolved in 09f0a2be3bc390bd74adebba4c4e37620b37e683 Let me know if you have any more issues! Release 0.0.12 has been created.
