### ISSUE TITLE
filtered queries return duplicateed first page

### ISSUE THREAD

**Issue by Exterminas** [MagicTheGathering/mtg-sdk-java#33]
MTGAPI.java row 115 adds the first page to the object list that is later returned. The for loop starting at row 121 then adds all pages to the object list which results in a duplicated page within the later returned list.
Deleting row 115 should solve the problem.

**Comment by thechucklingatom** [comment]
I apologize it took me so long to respond to this. I will attempt to get a test spun up this weekend to duplicate the issue, and will fix from there. Thank you for the report!

**Comment by thechucklingatom** [comment]
fixed with 3c0c04565755c3db5953d1c73943a1787b2b451a should be on maven shortly. I apologize it took me so long to get to it
